---
ci:
  # We rely on renovate to update it but there is no way to fully disable it
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - codespell
    - cspell
    - mypy
    - pylint
    - ruff
    - toml
    - yamllint
  submodules: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
        priority: 0
  - repo: https://github.com/ansible/actions
    rev: v1.1.0
    hooks:
      - id: toml
        priority: 0
      - id: mypy
        priority: 2
      - id: ruff
        priority: 1
      - id: cspell
        priority: 0
      - id: pylint
        priority: 5
      - id: codespell
        priority: 0
      - id: yamllint
        priority: 0
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.12
    hooks:
      - id: uv-sync
      - id: uv-lock
      - id: uv-lock
        name: "deps: upgrade via uv sync --upgrade"
        alias: deps
        args: ["--upgrade"]
        stages: [manual]
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.4.8"
    hooks:
      - id: biome-check
        name: biome
        alias: biome
        args: [--unsafe]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-symlinks
        priority: 0
      - id: debug-statements
        priority: 0
      - id: detect-private-key
        priority: 0
      - id: end-of-file-fixer
        priority: 1
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    # keep it after flake8
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
