---
site_name: Ansible MkDocs Theme
site_url: https://ansible.readthedocs.io/projects/mkdocs-ansible/
site_author: Ansible
site_description: >-
  This mkdocs theme is based on mkdocs-material and aims to provide a
  consistent look and feel for any project related to Ansible.
# Repository
repo_name: ansible/mkdocs-ansible
repo_url: https://github.com/ansible/mkdocs-ansible
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright 2024 Red Hat Inc

# Configuration
theme:
  name: ansible
  # custom_dir: src/mkdocs_ansible/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

nav:
  - Home: README.md
  - Macros: macros.md

# Plugins
plugins:
  - macros:
      modules: [mkdocs-ansible:mkdocs_ansible]
  - material/social
  - material/search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - material/tags
  - material/offline
  - minify:
      minify_html: true

# Customization
extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ansible/mkdocs-ansible
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-ansible/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
